name: Release

on:
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}

      - name: Release
        env:
          GITHUB_USER: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
          NPM_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        run: pnpm semantic-release
